spring:
  application:
    name: distributed-lock
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池最大阻塞等待时间（毫秒）（使用负值表示没有限制）
        max-wait: 30000

server:
  port: 8090